### ISSUE TITLE
Unsafe explicit type casting

### ISSUE THREAD

**Issue by lukas-h** [dartclub/dart_sort_queue#3]
https://github.com/dartclub/dart_sort_queue/blob/05478e6e3b12e935c5c319a644c6d0bab7a5b8d6/lib/src/dart_sort_queue_base.dart#L10

As I removed in my earlier commit, because this is extremely unsafe. This contradicts the whole usage of generic type T altogether..

@armantorkzaban

**Comment by armantorkzaban** [comment]
What about saying if 'T is int' then the default comparator?

**Comment by lukas-h** [comment]
I would say, that this is too limiting. Either we have it unsorted with "1" as the return val and no actual comparison and therefore no sorting. Or other option: We make the field compare mandatory/required.
I tend to the latter option, because then the user never encounters unexpected sorting and always has to explicitly set the comparison closure.

**Comment by armantorkzaban** [comment]
I would take the 2nd option too. Thanks
